---
- name: Test powershell script
  ansible.windows.win_powershell:
    script: |
      echo "Hello world"
  register: _echo_output
  delegate_to: "{{ _hvdeploy_target_host }}"

- debug: var=_echo_output.output

- name: Powershell version
  ansible.windows.win_powershell:
    script: |
      $PSVersionTable.PSVersion
  register: _ps_version
  delegate_to: "{{ _hvdeploy_target_host }}"

- debug: var=_ps_version.output

- name: Input variable test
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $Name
      )
      echo "Hello $Name"
    parameters:
      Name: "{{ _hvdeploy_target_host }}"
  register: _var_test_output
  delegate_to: "{{ _hvdeploy_target_host }}"

- debug: var=_var_test_output.output

- name: Inline variable test
  ansible.windows.win_powershell:
    script: |
      $Name = "{{ _hvdeploy_target_host }}"
      echo "Hello $Name"
  register: _inline_var_test_output
  delegate_to: "{{ _hvdeploy_target_host }}"

- debug: var=_inline_var_test_output.output

- name: SCVMM test
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $InputVMServer,
          [String]
          $InputVMName
      )

      Get-SCVirtualMachine -VMMServer $InputVMServer -Name $InputVMName
    parameters:
      InputVMServer: "mvscvmm01.pgsm.hu"
      InputVMName: "tvbw16std"
  register: _vm_result
  delegate_to: "{{ _hvdeploy_target_host }}"

- debug: var=_vm_result.output
